import Header from "@/components/layout/Header";
import { ThemeProvider } from "../context/theme-provider";
import "./globals.css";
import { Archivo } from "next/font/google";

const archivo = Archivo({ weight: "variable", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <ThemeProvider>
          <Header />
          <main>{children}</main>
          {/* <Footer /> */}
        </ThemeProvider>
        {/* <AppHooks /> */}
      </body>
    </html>
  );
}
